export const SELECT_HISTORY  = 'SELECT_HISTORY';
export const DELETE_HISTORY  = 'DELETE_HISTORY';
export const COPY_HISTORY_TO_CLIPBOARD = 'COPY_HISTORY_TO_CLIPBOARD';
export const CHANGE_HISTORY_TEXT = 'CHANGE_HISTORY_TEXT';
